### ISSUE TITLE
Link on docs website goes 404

### ISSUE THREAD

**Issue by corneliusroemer** [sdegutis/imlib-template-minimal#1]
This is 404: https://sdegutis.github.io/imlib-template/

from here:
first demo
https://code.immaculatalibrary.com/demos.html

**Comment by sdegutis** [comment]
Fixed, thanks.

**Comment by sdegutis** [comment]
Is your name actually Cornelius btw? That's so cool.

**Comment by corneliusroemer** [comment]
It is 😀 why is it cool? Cornelius Fudge? Not a positive character 🙈

**Comment by sdegutis** [comment]
haha no Latin names are just cool I guess

**Comment by corneliusroemer** [comment]
It's a bit of a pun by my parents as my surname means "(the) Roman" in German. My sister's name is Laetitia. 😂
